version: "3.3"  # optional since v1.27.0
services:
    serveurjwt:
      build: ./JWT
      expose:
        - "5835"
        - "5735"
    ressourceprotegee:
      build: ./RessourceProtegee
      expose:
        - "5001"
    frontend:
      build: ./Frontend
      ports:
        - "5000:5000"
    db:
      build: ./db
      expose:
        - "5002"
    mongodb:
      image: mongo:latest
      expose:
        - "27017"